name: Docker Image CI
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Setup buildx 
      uses: docker/setup-buildx-action@v1
    - name: Build and publish
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/emby_exporter:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/emby_exporter:${{github.ref_name}}
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/emby_exporter:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/emby_exporter:buildcache,mode=max
